const BASE='http://127.0.0.1:8080/api/v1'
const cachedImages=new Map()
function clear(preserveDrafts=false){getApp().globalData.preserveDrafts=preserveDrafts;if(!preserveDrafts)getApp().globalData.drafts={};wx.removeStorageSync('token');wx.removeStorageSync('user');getApp().globalData.user=null;for(const path of cachedImages.values())wx.getFileSystemManager().unlink({filePath:path,fail(){}});cachedImages.clear()}
function query(values){return Object.entries(values).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(v)).join('&')}
function request(path,options={}){return new Promise((resolve,reject)=>{const header={'Content-Type':'application/json'};const token=wx.getStorageSync('token');if(token)header.Authorization='Bearer '+token;if(options.etag)header['If-Match']=options.etag;if(options.key)header['Idempotency-Key']=options.key;wx.request({url:BASE+path,method:options.method||'GET',data:options.data,header,success(res){const body=res.data&&typeof res.data==='object'?res.data:{msg:'服务暂不可用，请稍后重试。填写内容已保留。'};if(res.statusCode>=200&&res.statusCode<300&&body.code===1){resolve(body.data);return}const error=Object.assign(new Error(body.msg||'请求失败，请重试'),{code:body.code,status:res.statusCode,fields:body.errors||[]});if(['AUTH_REQUIRED','TOKEN_EXPIRED','TOKEN_REVOKED','ACCOUNT_DISABLED','IDENTITY_UNVERIFIED'].includes(body.code)){clear(true);const pages=getCurrentPages();if(pages[pages.length-1]?.route!=='pages/login/login')wx.reLaunch({url:'/pages/login/login'})}if(body.code==='PASSWORD_CHANGE_REQUIRED'){wx.redirectTo({url:'/pages/account/account?forced=1'})}reject(error)},fail(){reject(new Error('网络连接失败，请检查服务后重试。填写内容已保留。'))}})})}
async function login(data){getApp().globalData.preserveDrafts=false;const result=await request('/auth/tokens',{method:'POST',data:{...data,client_type:'miniapp'}});wx.setStorageSync('token',result.access_token);wx.setStorageSync('user',result.user);getApp().globalData.user=result.user;if(result.user.must_change_password){wx.redirectTo({url:'/pages/account/account?forced=1'});return false}const user=await request('/users/me');wx.setStorageSync('user',user);getApp().globalData.user=user;return true}
function guard(){if(!wx.getStorageSync('token')){wx.reLaunch({url:'/pages/login/login'});return false}return true}
function image(url){if(!url)return Promise.resolve('');if(cachedImages.has(url))return Promise.resolve(cachedImages.get(url));const token=wx.getStorageSync('token');return new Promise(resolve=>wx.downloadFile({url:url.startsWith('/')?'http://127.0.0.1:8080'+url:url,header:{Authorization:'Bearer '+token},success(res){if(res.statusCode===200&&token===wx.getStorageSync('token')){cachedImages.set(url,res.tempFilePath);resolve(res.tempFilePath)}else resolve('')},fail(){resolve('')}}))}
function upload(path,size){if(size>5*1024*1024)return Promise.reject(new Error('单张图片不能超过 5 MB'));return new Promise((resolve,reject)=>wx.uploadFile({url:BASE+'/users/me/image-uploads',filePath:path,name:'file',header:{Authorization:'Bearer '+wx.getStorageSync('token')},success(res){let body;try{body=JSON.parse(res.data);if(!body||typeof body!=='object')throw new Error('invalid response')}catch{reject(new Error('上传失败，请重试'));return}if(body.code===1)resolve(body.data);else reject(new Error(body.msg||'上传失败'))},fail(){reject(new Error('上传失败，请检查网络后重试'))}}))}
function wxCode(){return new Promise((resolve,reject)=>wx.login({success:r=>r.code?resolve(r.code):reject(new Error('未能获取微信登录凭证')),fail:()=>reject(new Error('微信服务暂不可用'))}))}
module.exports={request,query,login,guard,clear,image,upload,wxCode}
