const BASE='http://127.0.0.1:8080/api/v1'
const cachedImages=new Map()
function clear(preserveDrafts=false){getApp().globalData.preserveDrafts=preserveDrafts;if(!preserveDrafts)getApp().globalData.drafts={};wx.removeStorageSync('token');wx.removeStorageSync('user');getApp().globalData.user=null;for(const path of cachedImages.values())wx.getFileSystemManager().unlink({filePath:path,fail(){}});cachedImages.clear();while(imageQueue.length)imageQueue.shift().finish('')}
function query(values){return Object.entries(values).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(v)).join('&')}
function request(path,options={}){return new Promise((resolve,reject)=>{const header={'Content-Type':'application/json'};const token=wx.getStorageSync('token');if(token)header.Authorization='Bearer '+token;if(options.etag)header['If-Match']=options.etag;if(options.key)header['Idempotency-Key']=options.key;wx.request({url:BASE+path,method:options.method||'GET',data:options.data,header,success(res){const body=res.data&&typeof res.data==='object'?res.data:{msg:'服务暂不可用，请稍后重试。填写内容已保留。'};if(res.statusCode>=200&&res.statusCode<300&&body.code===1){resolve(body.data);return}const error=Object.assign(new Error(body.msg||'请求失败，请重试'),{code:body.code,status:res.statusCode,fields:body.errors||[]});if(['AUTH_REQUIRED','TOKEN_EXPIRED','TOKEN_REVOKED','ACCOUNT_DISABLED','IDENTITY_UNVERIFIED'].includes(body.code)){clear(true);const pages=getCurrentPages();if(pages[pages.length-1]?.route!=='pages/login/login')wx.reLaunch({url:'/pages/login/login'})}if(body.code==='PASSWORD_CHANGE_REQUIRED'){wx.redirectTo({url:'/pages/account/account?forced=1'})}reject(error)},fail(){reject(new Error('网络连接失败，请检查服务后重试。填写内容已保留。'))}})})}
async function login(data){getApp().globalData.preserveDrafts=false;const result=await request('/auth/tokens',{method:'POST',data:{...data,client_type:'miniapp'}});wx.setStorageSync('token',result.access_token);wx.setStorageSync('user',result.user);getApp().globalData.user=result.user;if(result.user.must_change_password){wx.redirectTo({url:'/pages/account/account?forced=1'});return false}const user=await request('/users/me');wx.setStorageSync('user',user);getApp().globalData.user=user;return true}
function guard(){if(!wx.getStorageSync('token')){wx.reLaunch({url:'/pages/login/login'});return false}return true}
// 三个下载槽位，避免大图并发挤占带宽；同一账号和 URL 共用进行中的下载。
const pendingImages=new Map(),imageQueue=[]
let activeImages=0
function imageURL(url,size='original'){return url&&size!=='original'?url+(url.includes('?')?'&':'?')+'size='+size:url}
function drainImages(){while(activeImages<3&&imageQueue.length){const job=imageQueue.shift();if(job.token!==wx.getStorageSync('token')){job.finish('');continue}activeImages++;wx.downloadFile({url:job.url.startsWith('/')?'http://127.0.0.1:8080'+job.url:job.url,header:{Authorization:'Bearer '+job.token},success(res){if(res.statusCode===200&&job.token===wx.getStorageSync('token')){cachedImages.set(job.key,res.tempFilePath);job.finish(res.tempFilePath)}else{if(res.tempFilePath)wx.getFileSystemManager().unlink({filePath:res.tempFilePath,fail(){}});job.finish('')}},fail(){job.finish('')},complete(){activeImages--;drainImages()}})}}
function image(url,size='original'){if(!url)return Promise.resolve('');url=imageURL(url,size);const token=wx.getStorageSync('token'),key=token+':'+url;if(cachedImages.has(key))return Promise.resolve(cachedImages.get(key));if(pendingImages.has(key))return pendingImages.get(key);let finish;const result=new Promise(resolve=>{finish=value=>{pendingImages.delete(key);resolve(value)}});pendingImages.set(key,result);imageQueue.push({url,token,key,finish});drainImages();return result}
// 先显示文字，再逐张填充图片；页面卸载或新查询开始后不回写旧结果。
function loadImages(page,sources,generation=page.generation){for(const source of sources)image(source.url,source.size||'display').then(path=>{if(page.generation===generation)page.setData({[source.path]:path,...(source.errorPath?{[source.errorPath]:!!source.url&&!path}:{})})})}

function upload(path,size){if(size>5*1024*1024)return Promise.reject(new Error('单张图片不能超过 5 MB'));return new Promise((resolve,reject)=>wx.uploadFile({url:BASE+'/users/me/image-uploads',filePath:path,name:'file',header:{Authorization:'Bearer '+wx.getStorageSync('token')},success(res){let body;try{body=JSON.parse(res.data);if(!body||typeof body!=='object')throw new Error('invalid response')}catch{reject(new Error('上传失败，请重试'));return}if(body.code===1)resolve(body.data);else reject(new Error(body.msg||'上传失败'))},fail(){reject(new Error('上传失败，请检查网络后重试'))}}))}
function wxCode(){return new Promise((resolve,reject)=>wx.login({success:r=>r.code?resolve(r.code):reject(new Error('未能获取微信登录凭证')),fail:()=>reject(new Error('微信服务暂不可用'))}))}
module.exports={request,query,login,guard,clear,image,imageURL,loadImages,upload,wxCode}
