import { readFileSync, writeFileSync } from 'node:fs'
const source=readFileSync(new URL('../src/domain.js',import.meta.url),'utf8')
const names=[...source.matchAll(/export (?:const|function) (\w+)/g)].map(m=>m[1])
writeFileSync(new URL('../../miniprogram/utils/domain.js',import.meta.url),'// Generated by frontend/scripts/sync-domain.js; edit frontend/src/domain.js.\n'+source.replaceAll('export ','')+'\nmodule.exports={'+names.join(',')+'}\n')
