<script setup>
import { ref } from 'vue'
import { request, session, clearSession, logout } from '../api'
import { passwordError, dateTime } from '../domain'
const props=defineProps({forced:Boolean})
const editing=ref(props.forced), old=ref(''), password=ref(''), confirm=ref(''), error=ref(''), busy=ref(false)
async function save(){if(busy.value)return; error.value=passwordError(old.value,password.value,confirm.value); if(error.value)return; busy.value=true; try {await request('/users/me/password',{method:'PUT',data:{current_password:old.value,new_password:password.value}}); clearSession();session.notice='密码已修改，请使用新密码重新登录。'}catch(e){error.value=e.message}finally{busy.value=false}}
async function exit(){try{await logout()}catch(e){error.value=e.message}}
</script>
<template><section :class="forced?'forced-account container narrow':'narrow'"><header class="page-heading"><span class="eyebrow">ACCOUNT</span><h1>{{forced?'设置你的新密码':'账号设置'}}</h1><p>{{forced?'为保护账号，请先修改临时密码后继续使用。':'你的校园身份与登录安全'}}</p></header><div v-if="!editing" class="panel"><h2>账号资料</h2><dl class="facts"><dt>昵称</dt><dd>{{session.user.nickname}}</dd><dt>学号 / 职工号</dt><dd>{{session.user.account_no}}</dd><dt>身份</dt><dd>{{session.user.identity_type==='student'?'学生':'教职工'}}</dd><dt>验证状态</dt><dd>{{session.user.is_verified?'已验证':'未验证'}}</dd><dt>微信绑定</dt><dd>{{session.user.wechat_bound?'已绑定':'未绑定'}}<small v-if="session.user.wechat_bound_at">{{dateTime(session.user.wechat_bound_at)}}</small></dd></dl><p class="fine">账号资料由平台维护。绑定或更换微信，请在小程序中操作。</p><hr><div class="row between"><div><h3>登录密码</h3><p class="muted">已设置</p></div><button class="secondary" @click="editing=true">修改密码</button></div><button class="danger wide" @click="exit">退出所有端登录</button></div><form v-else class="panel" @submit.prevent="save"><label>当前密码<input v-model="old" type="password" autocomplete="current-password" required></label><label>新密码<input v-model="password" type="password" autocomplete="new-password" required><small>8–32 个字符，不能与当前密码相同。</small></label><label>确认新密码<input v-model="confirm" type="password" autocomplete="new-password" required></label><p class="notice">修改成功后，所有端的旧登录都会失效，请重新登录。</p><p v-if="error" class="error" role="alert">{{error}}</p><div class="row"><button class="primary" :disabled="busy">{{busy?'正在修改…':'确认修改'}}</button><button v-if="!forced" type="button" class="secondary" :disabled="busy" @click="editing=false">取消</button><button v-else type="button" class="text-button" @click="exit">退出登录</button></div></form></section></template>
