<script>const queueState = new Map()</script>
<script setup>
import { computed, reactive, ref, onMounted } from 'vue'
import { request, query } from '../api'
import { reviewLabels, reportLabels, reasons, campuses, actions, resolution, dateTime } from '../domain'
import State from '../components/State.vue'
import Modal from '../components/Modal.vue'
import Pagination from '../components/Pagination.vue'
import PostContent from '../components/PostContent.vue'
const props=defineProps({route:String})
const section=props.route.split('/')[0],id=props.route.split('/')[1]
const names={reviews:'帖子审核',reports:'举报处理',posts:'帖子管理',users:'账号管理',logs:'操作记录'}
const endpoint=section==='logs'?'operation-logs':section
const rows=ref([]),detail=ref(null),current=ref(null),history=ref([]),page=ref(1),total=ref(0),loading=ref(true),error=ref(''),busy=ref(false),modal=ref(''),reason=ref(''),actionError=ref(''),temporary=ref(''),copied=ref(false),conflict=ref(false),snapshotImages=ref([])
const filters=reactive(section==='reviews'?{decision:'pending',post_id:''}:section==='reports'?{status:'pending',post_id:''}:section==='users'?{account_no:'',nickname:'',status:'',identity_type:''}:section==='posts'?{keyword:'',campus:'',post_type:'',review_status:'',resolution_status:'',author_id:''}:{operator_id:'',action:'',target_post_id:'',target_user_id:'',created_from:'',created_to:''})
const titles={approved:'通过审核',returned:'退回修改',rejected:'拒绝发布',remove:'下架帖子',dismissed:'驳回举报',remove_post:'处理并下架帖子',disable_user:'处理并禁用账号',disable:'禁用账号',reset:'重置密码'}
const targetLabel=computed(()=>section==='users'?`账号：${detail.value?.nickname}（${detail.value?.account_no}）`:section==='reports'?`举报 #${id} · 帖子 #${detail.value?.post_id}`:section==='reviews'?`帖子：${detail.value?.content_snapshot?.item_name} · 第 ${detail.value?.revision} 版`:`帖子：${detail.value?.item_name}（#${id}）`)
const canRemove=computed(()=>detail.value?.review_status==='approved'&&detail.value?.resolution_status!=='withdrawn')
const savedQueue=queueState.get(section)
if(savedQueue)Object.assign(filters,savedQueue.filters)
async function load(p=1){loading.value=true;error.value='';conflict.value=false;try{if(id){detail.value=await request(`/admin/${endpoint}/${id}`);if(section==='reviews')snapshotImages.value=(detail.value.content_snapshot.images||[]).map((_,i)=>`/api/v1/posts/${detail.value.post_id}/reviews/${id}/images/${i}`);if(section==='reports'){current.value=await request('/admin/posts/'+detail.value.post_id);const reviews=await allReviews(detail.value.post_id);const original=reviews.find(r=>r.revision===detail.value.post_revision);snapshotImages.value=original?(original.content_snapshot.images||[]).map((_,i)=>`/api/v1/posts/${detail.value.post_id}/reviews/${original.id}/images/${i}`):[]}if(section==='posts')history.value=await allReviews(id)}else{page.value=p;queueState.set(section,{page:p,filters:{...filters}});const f={...filters};for(const k of ['created_from','created_to'])if(f[k])f[k]=new Date(f[k]+':00+08:00').toISOString();const data=await request('/admin/'+endpoint+'?'+query({...f,page:p,page_size:12}));rows.value=data.records;total.value=data.total}}catch(e){error.value=e.message}finally{loading.value=false}}
async function allReviews(postId){let result=[],p=1,data;do{data=await request(`/posts/${postId}/reviews?page=${p++}&page_size=50`);result.push(...data.records)}while(result.length<data.total);return result}
function open(action){modal.value=action;reason.value='';actionError.value=''}
async function decide(){if(busy.value)return;if((modal.value!=='approved'&&!reason.value.trim())||[...reason.value].length>500){actionError.value='请填写 1–500 字的原因';return}busy.value=true;actionError.value='';try{let path=`/admin/${endpoint}/${id}`,method='PUT',data,etag=detail.value.etag;const a=modal.value;if(section==='reviews'){path+='/decision';data={decision:a,reason:reason.value||null}}else if(section==='reports'){path+='/decision';data={status:a==='dismissed'?'dismissed':'handled',result_action:a==='dismissed'?'none':a,handling_reason:reason.value};if(a==='remove_post')data.expected_post_state_version=detail.value.current_post.state_version}else if(section==='posts'){path+='/moderation';method='PATCH';data={review_status:'removed',reason:reason.value}}else if(section==='users'){path+=a==='reset'?'/password-resets':'/status';method=a==='reset'?'POST':'PATCH';data=a==='reset'?{reason:reason.value}:{status:'disabled',reason:reason.value}}
const result=await request(path,{method,data,etag});modal.value='';if(a==='reset'){temporary.value=result.temporary_password;copied.value=false}else await load()}catch(e){actionError.value=e.message;conflict.value=e.status===412||e.status===409;if(modal.value==='reset')actionError.value+='。若响应丢失，请先核实操作记录，不要直接重复提交。'}finally{busy.value=false}}
async function copyPassword(){try{await navigator.clipboard.writeText(temporary.value);copied.value=true}catch{actionError.value='无法复制，请选中文字手动复制'}}
onMounted(()=>load(savedQueue?.page||1))
</script>
<template><header class="page-heading"><span class="eyebrow">CAMPUS MANAGEMENT</span><div class="row between"><h1>{{names[section]||'管理工作台'}}</h1><a v-if="id" :href="'#'+section" class="secondary">← 返回列表</a></div><p>{{section==='reviews'?'认真核对每条信息，让校园信息清晰、可信。':section==='reports'?'根据举报时的内容与当前状态作出处理。':section==='logs'?'每一次管理操作，都有记录可查。':'查看记录并完成相应管理操作。'}}</p></header>
<form v-if="!id" class="panel filter-row admin-filters" @submit.prevent="load()">
<template v-if="section==='reviews'"><label>审核决定<select v-model="filters.decision"><option v-for="(name,key) in reviewLabels" v-show="key!=='removed'" :value="key">{{name}}</option></select></label><label>帖子 ID<input v-model="filters.post_id" inputmode="numeric" placeholder="输入帖子 ID"></label></template>
<template v-if="section==='reports'"><label>处理状态<select v-model="filters.status"><option v-for="(name,key) in reportLabels" :value="key">{{name}}</option></select></label><label>帖子 ID<input v-model="filters.post_id" inputmode="numeric"></label></template>
<template v-if="section==='posts'"><label>关键词<input v-model="filters.keyword" placeholder="物品、地点或描述"></label><label>校区<select v-model="filters.campus"><option value="">全部</option><option v-for="(name,key) in campuses" :value="key">{{name}}</option></select></label><label>类型<select v-model="filters.post_type"><option value="">全部</option><option value="lost">寻物</option><option value="found">拾物</option></select></label><label>审核状态<select v-model="filters.review_status"><option value="">全部</option><option v-for="(name,key) in reviewLabels" v-show="key!=='superseded'" :value="key">{{name}}</option></select></label><label>处理状态<select v-model="filters.resolution_status"><option value="">全部</option><option value="active">进行中</option><option value="completed">已完成</option><option value="withdrawn">已撤回</option></select></label><label>作者 ID<input v-model="filters.author_id" inputmode="numeric"></label></template>
<template v-if="section==='users'"><label>学号 / 职工号<input v-model="filters.account_no" placeholder="完整账号"></label><label>昵称<input v-model="filters.nickname" placeholder="搜索昵称"></label><label>状态<select v-model="filters.status"><option value="">全部</option><option value="active">正常</option><option value="disabled">已禁用</option></select></label><label>身份<select v-model="filters.identity_type"><option value="">全部</option><option value="student">学生</option><option value="staff">教职工</option></select></label></template>
<template v-if="section==='logs'"><label>操作人 ID<input v-model="filters.operator_id" inputmode="numeric"></label><label>操作类型<select v-model="filters.action"><option value="">全部</option><option v-for="(name,key) in actions" :value="key">{{name}}</option></select></label><label>帖子 ID<input v-model="filters.target_post_id" inputmode="numeric"></label><label>用户 ID<input v-model="filters.target_user_id" inputmode="numeric"></label><label>开始时间（北京时间）<input v-model="filters.created_from" type="datetime-local"></label><label>结束时间（不含）<input v-model="filters.created_to" type="datetime-local"></label></template><button class="primary">查询</button></form>
<State :loading="loading" :error="error" :empty="!id&&!rows.length" @retry="load(page)"/>
<div v-if="!loading&&!error&&!id&&rows.length" class="panel table-panel"><table><thead><tr v-if="section==='reviews'"><th>记录 ID</th><th>帖子</th><th>版本</th><th>审核决定</th><th>提交时间</th><th></th></tr><tr v-else-if="section==='reports'"><th>举报 ID</th><th>帖子 ID</th><th>原因</th><th>举报人</th><th>状态</th><th>举报时间</th><th></th></tr><tr v-else-if="section==='posts'"><th>物品</th><th>校区</th><th>作者</th><th>审核状态</th><th>处理状态</th><th></th></tr><tr v-else-if="section==='users'"><th>账号</th><th>昵称</th><th>身份</th><th>角色</th><th>状态</th><th></th></tr><tr v-else><th>操作人</th><th>操作</th><th>帖子 ID</th><th>用户 ID</th><th>时间</th><th></th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><template v-if="section==='reviews'"><td>{{r.id}}</td><td><strong>{{r.content_snapshot.item_name}}</strong><small>ID {{r.post_id}}</small></td><td>第 {{r.revision}} 版</td><td><span class="badge" :class="r.decision">{{reviewLabels[r.decision]}}</span></td><td>{{dateTime(r.submitted_at)}}</td></template><template v-else-if="section==='reports'"><td>{{r.id}}</td><td>{{r.post_id}}</td><td>{{reasons[r.reason_type]}}</td><td>{{r.reporter.nickname}}</td><td><span class="badge" :class="r.status">{{reportLabels[r.status]}}</span></td><td>{{dateTime(r.created_at)}}</td></template><template v-else-if="section==='posts'"><td><strong>{{r.item_name}}</strong><small>ID {{r.id}}</small></td><td>{{campuses[r.campus]}}</td><td>{{r.author.nickname}}<small>ID {{r.author_id}}</small></td><td><span class="badge" :class="r.review_status">{{reviewLabels[r.review_status]}}</span></td><td>{{resolution(r)}}</td></template><template v-else-if="section==='users'"><td>{{r.account_no}}<small>ID {{r.id}}</small></td><td>{{r.nickname}}</td><td>{{r.identity_type==='student'?'学生':'教职工'}}</td><td>{{r.role==='admin'?'管理员':'普通用户'}}</td><td><span class="badge" :class="r.status">{{r.status==='active'?'正常':'已禁用'}}</span></td></template><template v-else><td>{{r.operator.nickname}}<small>ID {{r.operator.id}}</small></td><td>{{actions[r.action]}}</td><td>{{r.target_post_id||'—'}}</td><td>{{r.target_user_id||'—'}}</td><td>{{dateTime(r.created_at)}}</td></template><td><a :href="'#'+section+'/'+r.id">查看 →</a></td></tr></tbody></table><Pagination :page="page" :total="total" @change="load"/></div>
<template v-if="detail&&!loading&&!error">
<div v-if="section==='reviews'" class="detail-layout"><article class="panel"><span class="badge" :class="detail.decision">{{reviewLabels[detail.decision]}}</span><h2>{{detail.content_snapshot.item_name}}</h2><p class="fine">帖子 {{detail.post_id}} · 第 {{detail.revision}} 版 · {{dateTime(detail.submitted_at)}}</p><PostContent :post="detail.content_snapshot" :images="snapshotImages"/></article><aside class="panel detail-aside"><h2>审核决定</h2><p v-if="!detail.is_current" class="notice">这是旧版本，内容仅供查看。</p><p v-if="detail.reason">{{detail.reason}}</p><p class="fine">{{detail.reviewer?.nickname||'暂无人工审核记录'}}</p><template v-if="detail.can_decide"><button class="primary wide" @click="open('approved')">通过审核</button><button class="secondary wide" @click="open('returned')">退回修改</button><button class="danger wide" @click="open('rejected')">拒绝发布</button></template><p v-else class="muted">当前记录不可处理。</p><a :href="'#posts/'+detail.post_id">查看当前帖子 →</a></aside></div>
<template v-else-if="section==='reports'"><div class="panel"><div class="row between"><h2>举报 #{{detail.id}}</h2><span class="badge" :class="detail.status">{{reportLabels[detail.status]}}</span></div><p>{{reasons[detail.reason_type]}} · {{detail.reporter.nickname}} · {{dateTime(detail.created_at)}}</p><p class="preserve">{{detail.details||'无补充说明'}}</p><p v-if="detail.handling_reason" class="notice">处理原因：{{detail.handling_reason}}</p><div v-if="detail.can_decide" class="row"><button class="secondary" @click="open('dismissed')">驳回举报</button><button class="danger" @click="open('remove_post')">处理并下架帖子</button><button class="danger" @click="open('disable_user')">处理并禁用账号</button></div></div><div class="two-col report-comparison"><article class="panel"><h2>举报时内容 · 第 {{detail.post_revision}} 版</h2><p class="fine">保留举报提交时的内容快照</p><h3>{{detail.content_snapshot.item_name}}</h3><PostContent :post="detail.content_snapshot" :images="snapshotImages"/></article><article v-if="current" class="panel"><h2>当前内容 · 第 {{current.revision}} 版</h2><div class="row"><span class="badge" :class="current.review_status">{{reviewLabels[current.review_status]}}</span><span class="badge">{{resolution(current)}}</span></div><h3>{{current.item_name}}</h3><PostContent :post="current" :images="current.image_urls"/></article></div></template>
<div v-else-if="section==='posts'" class="detail-layout"><article class="panel"><h2>{{detail.item_name}}</h2><div class="row"><span class="badge" :class="detail.review_status">{{reviewLabels[detail.review_status]}}</span><span class="badge">{{resolution(detail)}}</span></div><p>{{detail.author.nickname}} · 第 {{detail.revision}} 版</p><PostContent :post="detail" :images="detail.image_urls"/></article><aside class="panel detail-aside"><button v-if="canRemove" class="danger wide" @click="open('remove')">下架帖子</button><h2>审核历史</h2><div v-for="r in history" class="timeline"><span class="badge" :class="r.decision">{{reviewLabels[r.decision]}}</span><h3>第 {{r.revision}} 版</h3><p>{{r.reason||'—'}}</p><p class="fine">{{dateTime(r.processed_at||r.submitted_at)}}</p><a :href="'#reviews/'+r.id">查看内容快照 →</a></div></aside></div>
<article v-else-if="section==='users'" class="panel narrow"><h2>{{detail.nickname}}</h2><dl class="facts"><dt>学号 / 职工号</dt><dd>{{detail.account_no}}</dd><dt>用户 ID</dt><dd>{{detail.id}}</dd><dt>身份</dt><dd>{{detail.identity_type==='student'?'学生':'教职工'}}</dd><dt>角色</dt><dd>{{detail.role==='admin'?'管理员':'普通用户'}}</dd><dt>状态</dt><dd>{{detail.status==='active'?'正常':'已禁用'}}</dd><dt>身份验证</dt><dd>{{detail.is_verified?'已验证':'未验证'}}</dd><dt>微信绑定</dt><dd>{{detail.wechat_bound?'已绑定':'未绑定'}}</dd><dt>创建时间</dt><dd>{{dateTime(detail.created_at)}}</dd></dl><div v-if="detail.role!=='admin'" class="form-actions"><button v-if="detail.status==='active'" class="danger" @click="open('disable')">禁用账号</button><button class="secondary" @click="open('reset')">重置密码</button></div><p v-else class="notice">管理员账号不提供禁用或重置入口。</p></article>
<article v-else-if="section==='logs'" class="panel"><h2>{{actions[detail.action]}}</h2><dl class="facts"><dt>操作人</dt><dd>{{detail.operator.nickname}}（{{detail.operator.id}}）</dd><dt>操作时间</dt><dd>{{dateTime(detail.created_at)}}</dd><dt>原因</dt><dd>{{detail.reason||'—'}}</dd><dt>帖子 / 用户 / 举报</dt><dd>{{detail.target_post_id||'—'}} / {{detail.target_user_id||'—'}} / {{detail.target_report_id||'—'}}</dd></dl><div class="two-col"><div><h3>操作前</h3><pre>{{JSON.stringify(detail.state_before,null,2)}}</pre></div><div><h3>操作后</h3><pre>{{JSON.stringify(detail.state_after,null,2)}}</pre></div></div></article>
</template>
<Modal v-if="modal" :title="titles[modal]" :busy="busy" @close="modal=''"><form @submit.prevent="decide"><p class="notice">{{targetLabel}}</p><p>{{modal==='disable'||modal==='disable_user'?'禁用后，该账号无法登录，其帖子将隐藏。当前版本不提供恢复入口。':modal==='reset'?'旧密码和所有端登录立即失效。临时密码仅在本次结果中显示，请线下交付本人。':modal==='approved'?'通过后，符合展示条件的帖子将在用户端公开。':'请核对对象与内容后提交处理。'}}</p><label>{{modal==='approved'?'审核说明（选填）':'处理原因 *'}}<textarea v-model="reason" rows="4" :required="modal!=='approved'"></textarea><small>{{[...reason].length}} / 500</small></label><p v-if="actionError" class="error" role="alert">{{actionError}}</p><div class="form-actions"><button v-if="conflict" type="button" class="secondary" @click="modal='';load()">重新查看最新状态</button><button v-else :class="modal==='approved'?'primary':'danger'" :disabled="busy">{{busy?'提交中…':'确认'+titles[modal]}}</button><button type="button" class="secondary" :disabled="busy" @click="modal=''">取消</button></div></form></Modal>
<Modal v-if="temporary" title="密码已重置" @close="temporary='';load()"><p>请立即保存并线下交付本人。关闭后无法再次查看此密码。</p><output class="temporary-password">{{temporary}}</output><button class="primary wide" @click="copyPassword">{{copied?'已复制':'复制临时密码'}}</button><p class="fine">用户下次登录必须修改临时密码。</p><p v-if="actionError" class="error">{{actionError}}</p></Modal>
</template>
