<script setup>
import { ref, reactive, onMounted } from 'vue'
import { request, query, session } from '../api'
import { reviewLabels, dateTime } from '../domain'
import State from '../components/State.vue'
import Pagination from '../components/Pagination.vue'
import PostCard from '../components/PostCard.vue'
const props=defineProps({tab:String})
const records=ref([]),page=ref(1),total=ref(0),loading=ref(true),error=ref(''),quota=ref(null),unread=ref(0),opened=ref(null)
const filters=reactive({review_status:'',resolution_status:'',read:'all'})
async function load(p=1){page.value=p;loading.value=true;error.value='';try{const notification=props.tab==='notifications';const [data,q,count]=await Promise.all([request((notification?'/notifications?':'/users/me/posts?')+query({...(notification?{read:filters.read}:{review_status:filters.review_status,resolution_status:filters.resolution_status}),page:p,page_size:12})),request('/users/me/post-quota'),request('/notifications/unread-count')]);records.value=data.records;total.value=data.total;quota.value=q;unread.value=count.count}catch(e){error.value=e.message}finally{loading.value=false}}
async function open(n){opened.value=opened.value===n.id?null:n.id;if(opened.value&&!n.read_at)try{const data=await request('/notifications/'+n.id+'/read-state',{method:'PUT',data:{read:true}});n.read_at=data.read_at;unread.value=Math.max(0,unread.value-1)}catch(e){error.value=e.message}}
onMounted(()=>load())
</script>
<template><header class="page-heading row between"><div><span class="eyebrow">MY CAMPUS</span><h1>{{session.user.nickname}}，你好</h1><p>管理你的发布，跟进每一条消息。</p></div><div v-if="quota" class="quota-card">今日还可发布 <strong>{{quota.remaining}}</strong> 篇<small>北京时间零点恢复 · 编辑不扣额度</small></div></header><nav class="tabs"><a href="#mine" :class="{active:tab==='posts'}">我的帖子</a><a href="#mine/notifications" :class="{active:tab==='notifications'}">我的通知 <span v-if="unread" class="count">{{unread}}</span></a><a href="#account">账号设置</a></nav><div class="filter-row panel"><template v-if="tab==='posts'"><label class="inline-label">审核状态<select v-model="filters.review_status" @change="load()"><option value="">全部</option><option v-for="(label,key) in reviewLabels" v-show="key!=='superseded'" :value="key">{{label}}</option></select></label><label class="inline-label">处理状态<select v-model="filters.resolution_status" @change="load()"><option value="">全部</option><option value="active">进行中</option><option value="completed">已完成</option><option value="withdrawn">已撤回</option></select></label><a href="#publish" class="primary small push-right">＋ 发布信息</a></template><label v-else class="inline-label">阅读状态<select v-model="filters.read" @change="load()"><option value="all">全部通知</option><option value="false">未读</option><option value="true">已读</option></select></label></div><State :loading="loading" :error="error" :empty="!records.length" @retry="load(page)"/><template v-if="!loading&&!error"><div v-if="tab==='posts'" class="post-grid"><PostCard v-for="post in records" :key="post.id" :post="post" own/></div><div v-else class="panel notification-list"><article v-for="n in records" :key="n.id"><button class="notification-title" :aria-expanded="opened===n.id" @click="open(n)"><span :class="{'unread-dot':!n.read_at}"></span><strong>{{n.title}}</strong><time>{{dateTime(n.created_at)}}</time><span>{{opened===n.id?'−':'＋'}}</span></button><div v-if="opened===n.id" class="notification-body"><p>{{n.content}}</p><a v-if="n.post_id" :href="'#post/'+n.post_id">查看相关帖子 →</a></div></article></div><Pagination v-if="total" :page="page" :total="total" @change="load"/></template></template>
